# Generated by Django 4.1.1 on 2022-09-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=1024)),
                ('ReleaseDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.actor')),
                ('Movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(fields=('Actor_id', 'Movie_id'), name='Relation'),
        ),
    ]
