# Generated by Django 4.1.1 on 2022-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Votes',
            field=models.IntegerField(default=0),
        ),
    ]
