# Generated by Django 4.1.1 on 2022-09-24 14:33

from sqlite3 import Date
from turtle import title
from django.db import migrations


def newMovie(apps,schema_editor):
    movie = apps.get_model('MovieApp','Movie')
    output = movie.objects.create(Title = 'Harry Potter', Description = 'Magical Realm',ReleaseDate = '2000-05-01',Votes = 0)
    print(output)

class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_movie_votes'),
    ]

    operations = [
        migrations.RunPython(newMovie)
    ]
